stages:
    - build
    - run
build:
    stage: build
    tags:
        - dind
    script:
        - docker build -t miniapp:latest .
run:
    stage: run
    tags: 
        - dind
    script:
        - docker rm -f miniapp || true
        - docker run -d -p 5173:5173 miniapp:latest --name miniapp
