stages:
    - build
    - run
build:
    stage: build
    tags:
        - dind
    script:
        - docker build miniapp .
run:
    stage: run
    tags: 
        - dind
    script:
        - docker run -p 5173:5173 miniapp
